import { operatorLanguageInstruction } from '../operator-language.mjs';
import { testSpecAgentInstruction } from '../test-spec.mjs';
import { fixedOperatorPrompt } from '../fixed-operator-profiles.mjs';

// Rendering only. Inputs have already been admitted by the round application service.
export function buildCandidateGenerationPrompt({
  mission, goal, workspace, baseline = {}, testMatrix = {}, workspaceInventory = [],
  experienceInstruction = '', boundaryInstruction = '',
}) {
  const baselineRunPy = baseline.oracleRunPy || baseline.materializer?.result?.runPy || '';
  const implementationInstruction = operatorLanguageInstruction(mission.implementation, mission.operatorProfile?.candidateContract);
  const executableTestInstruction = testSpecAgentInstruction(testMatrix);
  const frozenProfileInstruction = mission.operatorProfile ? fixedOperatorPrompt(mission.operatorProfile) : '';
  const inventoryText = workspaceInventory.length
    ? workspaceInventory.map((file) => `- ${file}`).join('\n')
    : '- (empty workspace)';
  return [
    'You are the local optimization Agent for Operator Studio.',
    `Mission ID: ${mission.id}`,
    `Goal: ${goal}`,
    `Target hardware: ${(mission.hardware || []).join(', ') || 'not specified'}`,
    `Metric: ${mission.metric || 'not specified'}`,
    `Workspace: ${workspace}`,
    'The Workspace is the isolated snapshot of the project-owned Iteration Repository. Only files changed inside this Workspace may become Candidate files.',
    'Read and write boundary: this Iteration Agent may access ONLY the Workspace above. Do not inspect parent directories, Source Registry, research/baseline directories, sibling projects, other test runs, or unrelated filesystem paths. Previous test-run code is forbidden input.',
    'Workspace file inventory at run start (authoritative):',
    inventoryText,
    'The first round may start without implementation code. Contract deliverables such as run.py may therefore be absent from the inventory. Do not Read or Edit an absent path: create it directly with a file creation or patch tool. The inline baseline below is prompt evidence and is not guaranteed to exist as workspace/run.py. Later rounds start from the current stable candidate.',
    'Inspect and edit only the configured implementation files. Do not search for another baseline. External references are optional implementation advice, not baseline authority.',
    implementationInstruction,
    frozenProfileInstruction ? `Frozen operator profile (immutable): ${frozenProfileInstruction}` : '',
    'Hard baseline constraint: before any optimized operator candidate can be adopted, Operator Studio must have a current valid baseline measured on the same runner and the same input shape. Prefer a PyTorch reference baseline expanded into a single-file run.py. If no authoritative upstream implementation exists, use a clearly labeled naive_v0 baseline derived from a v0 version and do not confuse it with an upstream reference.',
    `Baseline status: ${baseline.status || 'missing'}${baseline.evidence ? ` · ${baseline.evidence.environment} ${baseline.evidence.value}${baseline.evidence.unit}` : ''}${baseline.kind === 'naive_v0' ? ' · naive_v0' : ''}`,
    'The following baseline was generated by this Mission\'s Materializer and measured by the fixed workflow. Preserve its get_inputs() and reference(inputs) semantics while optimizing run(inputs):',
    '----- BEGIN CURRENT BASELINE RUN.PY -----',
    baselineRunPy,
    '----- END CURRENT BASELINE RUN.PY -----',
    'Runner contract: every candidate root run.py MUST remain the executable bridge and define get_inputs(), get_test_cases(), get_benchmark_inputs(), run(inputs), and reference(inputs). Native/Triton implementation files are selected by the language contract. A CLI-only benchmark, main(), or differently named entrypoints is invalid. Keep test inputs and reference semantics aligned with the established baseline, and optimize only the implementation path called by run(inputs).',
    mission.operatorProfile?.deliveryFiles?.length ? `Create and maintain these human-facing deliverables: ${mission.operatorProfile.deliveryFiles.join(', ')}. Update report.md with correctness, fixed benchmark measurements, the threshold chosen from the first correct Triton version, and each round's KEEP/DISCARD decision. run.py is an additional internal bridge and is not a substitute for any deliverable.` : '',
    executableTestInstruction,
    experienceInstruction,
    'Use the Mission baseline and iteration evidence embedded in this prompt. Create one bounded candidate patch inside the isolated Mission workspace. Do not call a remote benchmark service in this turn; Operator Studio owns the serialized test queue.',
    'Return one JSON object and no Markdown fences with this shape: {"schemaVersion":"operator-studio.agent-result/v1","summary":"...","diagnosis":{"summary":"...","bottlenecks":[]},"candidates":[{"id":"candidate-01","title":"...","hypothesis":"...","change":"...","files":["relative/path"],"sourceReferences":[],"risks":[]}],"recommendedCandidate":"candidate-01","nextAction":{"type":"candidate.plan","title":"...","reason":"...","expectedOutput":"...","risk":"medium"},"risks":[]}. List only files actually changed in the Mission workspace. If no candidate is justified, do not edit files; return an empty candidates array and explain why in summary.',
    'Do not decide whether human approval is required. Operator Studio applies its own policy to evidence and risk signals.',
    'For a resumed thread, follow the new user goal while keeping all work inside this isolated Mission workspace.',
    boundaryInstruction,
  ].join('\n');
}

