const frozen = (value) => Object.freeze(value);

export const runtimeDefinitions = frozen([
  frozen({
    id: 'claude-code',
    label: 'Claude Code Agent Runtime',
    authority: 'claude-code',
    name: 'Claude Code',
    slug: 'claude',
    unavailableCode: 'CLAUDE_RUNTIME_UNAVAILABLE',
    clientKey: 'claude',
    stateRuntimeKind: 'claude-code',
    transport: 'stdio-jsonl',
    eventParser: 'claude-stream-json',
    failureClassifier: 'claude',
    usageSemantics: 'anthropic',
    operations: frozen({
      describe: 'describe',
      preflight: 'preflight',
      start: 'start',
      readRun: 'readRun',
      readEvents: 'readEvents',
      cancel: 'cancel',
      eventText: 'eventText',
    }),
    configurationAuthority: 'local-claude-code',
    defaultStallMs: 5 * 60 * 1000,
    managedWorkspace: true,
    capabilities: frozen({
      research: true,
      materializer: true,
      iteration: true,
      workspaceWrite: true,
      webResearch: true,
      sessionResume: true,
      structuredEvents: true,
      cancellation: true,
      usageReporting: true,
    }),
  }),
  frozen({
    id: 'codex-cli',
    label: 'Codex Agent Runtime',
    authority: 'codex-cli',
    name: 'Codex',
    slug: 'codex',
    unavailableCode: 'CODEX_RUNTIME_UNAVAILABLE',
    clientKey: 'codex',
    stateRuntimeKind: 'codex-cli',
    transport: 'stdio-jsonl',
    eventParser: 'codex-jsonl',
    failureClassifier: 'codex',
    usageSemantics: 'openai',
    operations: frozen({
      describe: 'describe',
      preflight: 'preflight',
      start: 'start',
      readRun: 'readRun',
      readEvents: 'readEvents',
      cancel: 'cancel',
      eventText: 'eventText',
    }),
    configurationAuthority: 'local-codex',
    defaultStallMs: 2 * 60 * 1000,
    managedWorkspace: true,
    capabilities: frozen({
      research: true,
      materializer: true,
      iteration: true,
      workspaceWrite: true,
      webResearch: true,
      sessionResume: true,
      structuredEvents: true,
      cancellation: true,
      usageReporting: true,
    }),
  }),
  frozen({
    id: 'opencode-server',
    label: 'OpenCode Agent Runtime',
    authority: 'opencode',
    name: 'OpenCode',
    slug: 'opencode',
    unavailableCode: 'OPENCODE_RUNTIME_UNAVAILABLE',
    clientKey: 'opencode',
    stateRuntimeKind: 'opencode',
    transport: 'http-session',
    eventParser: 'opencode-session',
    failureClassifier: 'opencode',
    usageSemantics: 'opencode',
    operations: frozen({
      health: 'health',
      providers: 'providers',
      createSession: 'createSession',
      prompt: 'promptAsync',
      readStatus: 'sessionStatus',
      readEvents: 'messages',
      readDiff: 'diff',
      cancel: 'abort',
    }),
    configurationAuthority: 'local-opencode',
    defaultStallMs: 2 * 60 * 1000,
    managedWorkspace: false,
    capabilities: frozen({
      research: false,
      materializer: false,
      iteration: false,
      workspaceWrite: false,
      webResearch: false,
      sessionResume: false,
      structuredEvents: true,
      cancellation: true,
      usageReporting: true,
      planning: true,
    }),
  }),
]);
